theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/CircuitFlyer/Touch_and_Go/archive/refs/tags/v1.2.zip
  tar_url: https://github.com/CircuitFlyer/Touch_and_Go/archive/ref/tags/v1.2.tar.gz
