theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/CircuitFlyer/Touch_and_Go/archive/v1.2.zip
  tar_url: https://github.com/CircuitFlyer/Touch_and_Go/archive/v1.2.tar.gz
